<a href="https://colab.research.google.com/github/cbrgott/FCNN/blob/main/FCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [270]:
import numpy as np

In [271]:
def sserror(y_true, y_pred):
    return 0.5 * np.sum(np.power(y_pred - y_true, 2))

In [272]:
def actfunc(x, funct) :
    if funct == 'sigmoid' :
       f = 1/(1+np.exp(x))
    elif funct == 'tanh' :
       f = np.tanh(x)
    elif funct == 'Relu' :
       f =  np.maximum(0,x)
    else :
       f = x
    return f

In [273]:
def derivactfunc(x, funct) :
    if funct == 'sigmoid' :
       f = 1/(1+np.exp(x))
       df = f*(1-f)
    elif funct == 'tanh' :
       f = np.tanh(x)
       df = 1-f**2
    elif funct == 'Relu' :
       f =  np.maximum(0,x)
       df = f > 0
    else :
       df = 1
    return df

In [274]:
def forwardprop(X,W1,W2,B1,B2, funct1, funct2) :
    H1_preact = W1.dot(X)+B1
    H1_act = actfunc(H1_preact, funct1)
    Y_preact = W2.dot(H1_act)+B2
    Y_act = actfunc(Y_preact, funct2)
    return Y_act, Y_preact, H1_act, H1_preact

In [275]:
def backwardprop(X, y_true, Y_act, Y_preact, H1_act, H1_preact, W2, funct1, funct2): 
    dEY_act = (Y_act-y_true)
    dEY_preact = dEY_act*derivactfunc(Y_preact, funct2)
    dEW2 = dEY_preact.dot(H1_act.T)
    dEB2 = dEY_preact
    #print('dEW2:',dEW2.shape)
    #print('dEB2:',dEB2.shape)
    ###################
    dEH1_act = (W2.T).dot(dEY_preact)
    dEH1_preact = dEH1_act*derivactfunc(H1_preact, funct1)
    dEW1 = dEH1_preact.dot(X.T)
    dEB1 = dEH1_preact
    #print('dEW1:',dEW1.shape)
    #print('dEB1:',dEB1.shape)
    return dEB2, dEW2, dEB1, dEW1


In [276]:
def gradient_descent(B1, B2, W1, W2,dEB2, dEW2, dEB1, dEW1, learning_rate) :
    B1 = B1-learning_rate*dEB1
    B2 = B2-learning_rate*dEB2
    W1 = W1-learning_rate*dEW1
    W2 = W2-learning_rate*dEW2
    return B1, B2, W1, W2

In [277]:
def predict(x_test,W1,W2,B1,B2, funct1, funct2) :
    y_pred = forwardprop(x_test.T,W1,W2,B1,B2, funct1, funct2)[0].T
    return y_pred

In [278]:
def trainproc(x_train, y_train, input_layer, hidden_layer, output_layer, iteration, learning_rate, actfunct1,actfunct2 ) :
    np.random.seed(0)

    W1 = np.random.rand(hidden_layer, input_layer)
    B1 = np.random.rand(hidden_layer,1)
    W2 = np.random.rand(output_layer, hidden_layer)
    B2 = np.random.rand(output_layer,1)
    for i in range(iteration) :
        error = 0
        acc = 0
        for X, y_true in zip(x_train,y_train) :
            X = np.expand_dims(X, axis = 1)
            y_true = np.expand_dims(y_true,axis = 1)
            Y_act, Y_preact, H1_act, H1_preact = forwardprop(X,W1,W2,B1,B2, actfunct1, actfunct2)
            error = error +sserror(y_true,Y_act)
            dEB2, dEW2, dEB1, dEW1 = backwardprop(X, y_true, Y_act, Y_preact, H1_act, H1_preact, W2, actfunct1, actfunct2)
            B1, B2, W1, W2 = gradient_descent(B1, B2, W1, W2, dEB2, dEW2, dEB1, dEW1, learning_rate)
            if np.around(sum(y_true - Y_act)) == 0 :
                 acc = acc +1
        error = error/x_train.shape[0]
        acc = acc/x_train.shape[0]
        print('iteration :', i , 'error:', error, 'accuracy:', acc)
    return B1, B2, W1, W2
    

In [279]:
x_train = np.array([[0,0], [0,1], [1,0], [1,1]])
y_train = np.array([[0], [1], [1], [0]])

In [280]:
B1, B2, W1, W2 = trainproc(x_train, y_train, 2, 4, 1, 300, 0.1, 'tanh','Relu' )

iteration : 0 error: 0.28460305159807636 accuracy: 0.5
iteration : 1 error: 0.1764858374965017 accuracy: 0.5
iteration : 2 error: 0.18160156186062312 accuracy: 0.5
iteration : 3 error: 0.18137281961459412 accuracy: 0.5
iteration : 4 error: 0.1801999420591785 accuracy: 0.5
iteration : 5 error: 0.1790646648974692 accuracy: 0.5
iteration : 6 error: 0.17807790039336358 accuracy: 0.5
iteration : 7 error: 0.17722701311228922 accuracy: 0.5
iteration : 8 error: 0.17648808222153628 accuracy: 0.5
iteration : 9 error: 0.17584044106934188 accuracy: 0.5
iteration : 10 error: 0.1752675447050837 accuracy: 0.5
iteration : 11 error: 0.17475620999195485 accuracy: 0.5
iteration : 12 error: 0.174295859922439 accuracy: 0.5
iteration : 13 error: 0.17387793696534026 accuracy: 0.5
iteration : 14 error: 0.17349546106215205 accuracy: 0.5
iteration : 15 error: 0.173142695460957 accuracy: 0.5
iteration : 16 error: 0.17281489177205106 accuracy: 0.5
iteration : 17 error: 0.17250809359366787 accuracy: 0.5
iteration 

In [281]:
np.around(predict(x_train,W1,W2,B1,B2, 'tanh', 'Relu'))

array([[0.],
       [1.],
       [1.],
       [0.]])

In [282]:
y_train

array([[0],
       [1],
       [1],
       [0]])

In [283]:
import sklearn.datasets
X, Y = sklearn.datasets.make_moons(n_samples=500, noise=.2)
Y = Y.reshape(Y.shape[0],1)

In [284]:
x_train = X[0:495]
y_train = Y[0:495]
x_test =  X[495:]
y_test = Y[495:]

In [285]:
B1, B2, W1, W2 = trainproc(x_train, y_train, 2, 10, 1, 300, 0.1, 'tanh','tanh')

iteration : 0 error: 0.2007710402256259 accuracy: 0.5515151515151515
iteration : 1 error: 0.07546639763834204 accuracy: 0.7838383838383839
iteration : 2 error: 0.05814533870905948 accuracy: 0.8464646464646465
iteration : 3 error: 0.04857186453198324 accuracy: 0.8828282828282829
iteration : 4 error: 0.045033475411680866 accuracy: 0.898989898989899
iteration : 5 error: 0.04247481266355899 accuracy: 0.9090909090909091
iteration : 6 error: 0.039751243725124626 accuracy: 0.9232323232323232
iteration : 7 error: 0.03699592009327732 accuracy: 0.9292929292929293
iteration : 8 error: 0.03453769098664474 accuracy: 0.9353535353535354
iteration : 9 error: 0.03258129430378836 accuracy: 0.9333333333333333
iteration : 10 error: 0.031097810361929643 accuracy: 0.9414141414141414
iteration : 11 error: 0.029956524832292285 accuracy: 0.9454545454545454
iteration : 12 error: 0.029037569321542684 accuracy: 0.9494949494949495
iteration : 13 error: 0.028257041048353197 accuracy: 0.9515151515151515
iteration : 

In [286]:
np.around(predict(x_test,W1,W2,B1,B2, 'tanh', 'tanh'))

array([[ 1.],
       [ 1.],
       [ 1.],
       [-0.],
       [-0.]])

In [287]:
y_test

array([[1],
       [1],
       [1],
       [0],
       [0]])